version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '8080:80'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    environment:
      - MONGO_DB_CONNECTION_STRING=mongodb://mongodb:27017/sample
    stdin_open: true
    tty: true
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '8123:27017'
    volumes:     
      - dbdata:/data/db
 
networks:
   app-network:
    driver: bridge
    
volumes:
  dbdata: 
  node_modules: 
